name: docs

on:
  push:
    branches:
      - "main"
      - "metarepo"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
