name: docs

on:
  push:
    branches:
      - "main"
      - "metarepo"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate
        uses: ./.github/actions/rosdoc2
        with:
          rosdoc2_repo: "https://github.com/rkent/rosdoc2.git"
          rosdoc2_branch: "prerun_conf_py"
