name: docs

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # fetch full depth so we can get the docs branch
          fetch-depth: '0'

      - name: Set user
        uses: fregante/setup-git-user@v1

      - name: Merge main into docs
        run: git switch docs
      - run: git merge main -m "Merge main into docs"
      - run: git push

      - name: Generate documentation
        uses: ./.github/actions/rosdoc2
        with:
          rosdoc2_repo: "https://github.com/rkent/rosdoc2.git"
          rosdoc2_branch: "rkent/jinja-templates"

      - name: Update docs branch
        run: git add docs
      - run: git commit -m "Publish updated documents"
      - run: git push
